### PR TITLE
fix: program hanging if all dns resolution fail consecutively

### LINKED ISSUE #1029: Bug: Internet dropout skips update and never retries
**TLDR**: When the internet connection drops out, the update gets skipped and never tried again until the next change.

1. Is this urgent: YES
2. DNS provider(s) you use: DuckDNS
3. Program version:

`Running version 2.9.0 built on 2024-12-24T10:40:42.120Z (commit 78f3061)`

4. What are you using to run the container: TrueNAS "Apps" (aka TrueCharts)
5. Extra information: I've experienced this repeatedly, when the internet drops out, it fails to send an update, and then doesn't try again unless the container is stopped and restarted. What's worse, once I figured this out I saw in the logs that it only WARNS that it's doing this. It should probably be error? And also retry. The container crashing would even be better cause at least then I'd know there was a problem before I found myself unable to connect.

Logs:

```log
2025-08-15 08:20:15.375777+00:002025-08-15T18:20:15+10:00 ERROR obtaining ipv4 or ipv6 address: after 3 tries, errors were: Get "https://api.seeip.org": context deadline exceeded, dial tcp: lookup dns.opendns.com: i/o timeout, Get "https://ip.changeip.com": context deadline exceeded
2025-08-15 08:20:15.375902+00:002025-08-15T18:20:15+10:00 WARN Skipping update for REDACTED.duckdns.org because IP address was not found
```

Configuration file:

```json
{
  "settings": [
    {
      "domain": "duckdns.org",
      "ip_version": "",
      "provider": "duckdns",
      "token": "REDACTED"
    }
  ]
}
```

Host OS: TrueNAS Scale 24.20.2

### PR DESCRIPTION
**Pull request by eshirvana**
fix #1029

### CODE REVIEW

File: internal/update/service.go [hunk 1]
```diff
@@ -77,6 +77,10 @@ func (s *Service) lookupIPsResilient(ctx context.Context, hostname string, tries
 				results <- result{network: network, ips: ips, err: err}
 				return
 			}
+			results <- result{
+				network: network,
+				err:     fmt.Errorf("look up failed after %d tries.No IP address found", tries),
```
Comment (qdm12) [inline internal/update/service.go]:
```suggestion
				err:     fmt.Errorf("ip look up failed after %d tries", tries),
```

**Review by eshirvana — COMMENTED** [review]
sure

**Comment by qdm12** [comment]
Awesome, thanks for the fix. Shameful code right there 🤷

**Comment by virtualdj** [comment]
@qdm12 Thanks, can you push a release with this fix?

**Comment by virtualdj** [comment]
@qdm12 I'm asking again if you can please create a release that includes this fix.
Thanks!
